### ISSUE TITLE
Make jackson databind optional

### ISSUE THREAD

**Issue by kimchy** [FasterXML/jackson-dataformat-yaml#34]
Should databind be marked as optional in the pom file? I think it should, otherwise, it gets pulled when one doesn't need it? I see in others (like cbor) its just used in testing, btw

**Comment by cowtowncoder** [comment]
This is a tricky question. In most aspects, yes, it is used only for testing. The one exception is addition of `YAMLMapper`, convenience extension of `ObjectMapper`.

In practice you can exclude this dependency, and unless `YAMLMapper` was used, there is no harm. Although deployment on OSGi container might complain.

**Comment by cowtowncoder** [comment]
I think I will simply make databind dependency `provided`, and that hopefully allows avoiding it as desired.

**Comment by cowtowncoder** [comment]
Changed `jackson-databind` dependency `provided`, hope this helps.
