### ISSUE TITLE
Does not handle octal or hexadecimal representations of integers.

### ISSUE THREAD

**Issue by jvantuyl** [FasterXML/jackson-dataformat-yaml#37]
The use of BigInteger for really big integers introduces an interesting behavior.  For a very large zero-prefixed number, it won't see a leading zero as indicating octal (because BigInteger's constructor doesn't mirror Integer.parseInt or Long.parseLong).

In the long run, also doesn't support the 0o644 notation from YAML 1.2, which I'm starting to see floating about.

**Comment by jvantuyl** [comment]
Oh, wait.  I may have misread the docs. Integer.parseInt and Long.parseLong don't appear to support it either.  Does jackson-dataformat-yaml just not support any non-decimal representation for ints?

**Comment by cowtowncoder** [comment]
Ideally we would support all valid YAML values, to the degree SnakeYAML does. So there is no intent to limit use of octals. However, with YAML it is not always trivial to figure out proper coercions.

**Comment by jvantuyl** [comment]
No argument there.  One of the reasons I like YAML-1.2 is that stuff gets a lot clearer (though it's a long road for most parsers to get there).

The octal thing is used [quite a bit more than I expected](https://github.com/search?q=0644+language:YAML&type=Code&ref=searchresults).

**Comment by cowtowncoder** [comment]
Interesting, wrt `chmod` and other. Although many of the matches are quoted strings; and in other usages (like as arg for `chmod`) it could be used as implied string thing to interpolate too.

Anyway: one thing that could be useful would be simple unit test with octal value, being bound to an `int` property. I could work with that.

**Comment by cowtowncoder** [comment]
Modified title, hoping to work on this for 2.7; probably not earlier (although may not have to wait per se).

**Comment by cowtowncoder** [comment]
One useful thing here would be a set of test cases/examples. Supporting octal formats should be quite easy, but implementation will be more reliable with verification.

**Comment by cowtowncoder** [comment]
Moved -> https://github.com/FasterXML/jackson-dataformats-text/issues/3
