### ISSUE TITLE
Returning YAML with object references possible?

### ISSUE THREAD

**Issue by Xnyle** [FasterXML/jackson-dataformat-yaml#41]
I saw the discussion #20 about merging. There are a few mentions about object references but I'm not sure if my request belongs there as it is slightly different:

I'd like to transfer references over to the client side of a REST application. Thats the only reason why i need YAML, not JSON. 

I can do this easily using SnakeYAML alone and a simple wrapper that returns StreamingOutput.

But then I can't use Representers I already have for JSON.

So is there a possibility to configure the objectmapper to return object references and not to "copy objects"?

**Comment by cowtowncoder** [comment]
I am not 100% sure I understand the question here.

But just in case let me try to see if I can answer the question... yes, YAML has native Object Id/Ref scheme; and JSON uses alternative, in-band (as part of JSON content) mechanism. The two work slightly differently. By default YAML module expected use of native object (and type) ids, and will write them, expect anchor/ref style. But it is possible to force use of JSON-like in-band/in-data Object Ids, references.
`YAMLGenerator` has `Feature.USE_NATIVE_OBJECT_ID` (true by default) which indicates whether Object Ids are to be written as native anchor/tag, or as JSON-style ids.
There is no setting for `YAMLParser` so it may be that both are acceptable -- I forget the exact details, but I think that with 2.6, both approaches should actually work: parser checks native object id first; if one not found, expects as-property id.

Another thing to note is that even with Object Ids, POJO properties still must indicate whether such ids are to be used, with `@JsonIdentityInfo`. Without this marker, no identity-based serialization/deserialization is used or expected.

Not sure if this answers your question yet, but perhaps helps in giving more details and figuring out what to ask for.

**Comment by Xnyle** [comment]
Thanks for the reply, by looking up @JsonIdentityInfo if found a test https://github.com/FasterXML/jackson-dataformat-yaml/blob/master/src/test/java/com/fasterxml/jackson/dataformat/yaml/ObjectIdTest.java

But then I should get (without configuring anything):

referencedObj: &001
  referencedObjProp: true
referencedObjAgain: *001

Which is exactly what I need, but I get (which is strange):

referencedObj:
  referencedObjProp: true
referencedObjAgain:
  referencedObjProp: true

And then I end up with having two different object instances on the client side of my rest service.

If I use SnakeYaml alone I get the correct (first) output, so  referencedObj and referencedObjAgain are in fact the same object.

**Comment by cowtowncoder** [comment]
At this point what would make sense is a reproducible test case. Your expectation is correct wrt output, assuming you have a simple POJO with `@JsonIdentityInfo` annotation in it (or, attached to the property that refers to the object).

**Comment by Xnyle** [comment]
Ah @JsonIdentityInfo is a must have for this to work. Thanks for the hint.

http://wiki.fasterxml.com/JacksonFeatureObjectIdentity
http://wiki.fasterxml.com/JacksonMixInAnnotations

That's exactly what I need. Sorry for the confusion, the reason why I couldn't find this was because I started searching from this project's documentation and there is nothing in the WIKI linking to the main FasterXML documentation. I didn't even know object ids are possible for JSON.

Maybe you should add a sentence at the bottom of the WIKIs main page: If you came here because you'd like jackson to create YAML containing object references, first take a look at the two links above.

**Comment by cowtowncoder** [comment]
Good idea; and apologies for confusion.

**Comment by Xnyle** [comment]
Ok, next problem :) Is there an easy way to provide a Representer Implementation (from SnakeYaml) to the YAMLFactory? Or do I have to Implement a new ObjectCodec?

**Comment by cowtowncoder** [comment]
There is no way to plug-in SnakeYAML-specific handlers or abstraction per se; I am mostly thinking of opening up "simple" low-level configuration options at YAML format level.
If the goal is to change the structure being read or written, then standard Jackson abstractions work. For example, `Converter`-based serializer/deserializer might be a good bet, or combination of `@JsonValue` (method that returns representation to use instead of POJO itself) and `@JsonCreator` (where constructor can convert an incoming Map or POJO into type).

**Comment by Xnyle** [comment]
I already have implemeted all transformations  I need, as I use SnakeYaml for importing/exporting data and staging systems.
I would like to reuse that/not chnage that at all for REST. But maybe the whole approach of using a YAML Object mapper is just wrong and it's better to just reuse my existing transformation tools and let them produce a StreamingOutput.

Otherwise I would have to implement the same logic in different places and the longer I think about it, this logic doesn't even belong to the REST layer.

Anyway, thanks for your explanations.

**Comment by cowtowncoder** [comment]
@Xnyle Makes sense to me; things that already work are awesome. :)
