### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by okigan** [FasterXML/jackson-dataformat-yaml#46]
Seems date object are not handled correctly/consistently as in json. 

Is there a way to make date objects to show up as a timestamp? i.e. like configured wth:

```
objectMapper.configure(SerializationConfig.Feature.WRITE_DATES_AS_TIMESTAMPS, true); 
```

**Comment by cowtowncoder** [comment]
Can not reproduce at this point; may be refiled with a test.
