### ISSUE TITLE
Folded String has additional newline

### ISSUE THREAD

**Issue by drieselliott** [FasterXML/jackson-dataformat-yaml#47]
When parsing a value like:

```
  description: >
    This is a description
    Spanning multiple lines
```

The parser is adding an additional newline to the end of the parsed String.

**Comment by cowtowncoder** [comment]
Since underlying parsing is done using SnakeYAML, that would be handling decoding, and typically it follows semantics of YAML reasonably well. So I wonder if this might actually be intended behavior. It would be good to know what YAML specification thinks about the case.

**Comment by cowtowncoder** [comment]
Would need more information wrt SnakeYAML to know for sure; I also wonder yaml specification says.
At this point can not really do much.
