### ISSUE TITLE
YAML block/flow style output control

### ISSUE THREAD

**Issue by cruisercoder** [FasterXML/jackson-dataformat-yaml#52]
Jackson provides some control over the generated YAML, such as MINIMIZE_QUOTES. It it would also be nice also have control over the block/flow style at any point during the generation. This can be implemented by controlling the value of the style boolean that is passed to the snakeyaml Emitter.emit call.

**Comment by phauer** [comment]
+1, especially when it comes to arrays I sometimes prefer the flow notation which is more compact. It would be very nice, if I could specify a hint on the granularity of properties, whether the flow or the block notation should be used for a given array field.

**Comment by cowtowncoder** [comment]
@phauer Understood. The challenge comes from figuring out a way to support this via annotations, but using format-specific annotations -- unless a "more generic" `SerializationFeature` could be devised, as that can already be added on properties using `@JsonFormat`.
By "more general" I just mean naming for a feature that could conceivably be applicable with other formats as well -- perhaps along lines of "brief vs compactness". Such a distinction could be meaningful for other things.

Or, perhaps it could be direct property of `@JsonFormat` itself; there's fine balancing act to support smallish set of generally useful configuration options.

Then again, this would still only be part of the issue. `JsonGenerator` would need to somehow expose this for actual low-level calls, as databind (which handles all annotations) has to communicate the inten through somehow.

If the support only needed to be accessible from custom serializers it could be simple, as method could be just exposed on `YAMLGenerator`

**Comment by cowtowncoder** [comment]
Is `LITERAL_BLOCK_STYLE` (see #76) relevant here?

**Comment by cowtowncoder** [comment]
Moved: https://github.com/FasterXML/jackson-dataformats-text/issues/4
