### ISSUE TITLE
Inaccurate @since version for YAMLGenerator.Feature#MINIMIZE_QUOTES

### ISSUE THREAD

**Issue by willgorman** [FasterXML/jackson-dataformat-yaml#55]
The javadoc @since tag for [com.fasterxml.jackson.dataformat.yaml.YAMLGenerator.Feature#MINIMIZE_QUOTES](https://github.com/FasterXML/jackson-dataformat-yaml/blob/master/src/main/java/com/fasterxml/jackson/dataformat/yaml/YAMLGenerator.java#L78) says that it was added in 2.6 but it looks like it wasn't added until 2.7

**Comment by cowtowncoder** [comment]
Thanks, will change, good catch.

**Comment by cowtowncoder** [comment]
Most likely a cut'n paste error, but I should have noticed that when merging. Thank you for reporting this.
