### ISSUE TITLE
Check for valid Yaml

### ISSUE THREAD

**Issue by knguyen142** [FasterXML/jackson-dataformat-yaml#57]
When I run 

`SomeObject object = mapper.readValue(unparsed, SomeObject.class);`

where unparsed is an invalid yaml string (e.g. "hello"), the line does not throw an exception, unlike the json parser, and instead sets the unparsed string as a field in the object. Is there any way to validate the yaml string?

**Comment by cowtowncoder** [comment]
@knguyen142 I would need a full unit test, not general description.

But as a general rule, if it was _invalid_ YAML (that is, one that can not be decoded), it would throw an exception. So I assume it is valid in strict sense of being legal YAML
As to whether it is compatible with the object `SomeObject` I can not say without seeing code.

**Comment by knguyen142** [comment]
Hmm, it doesn't look like valid yaml (it was just a string with "404 page not found". The workaround I did was to run `new Yaml().load(unparsed)` of the same org.yaml.snakeyaml, which suggests it should be invalid yaml and not be loadable into any object. Yaml, which throws and exception. So with that, I'll close the Issue.

**Comment by cowtowncoder** [comment]
@knguyen142 That can't be right. Jackson uses SnakeYAML to decode YAML, so if it fails to decide it, Jackson will. So problem is somewhere else.

Anyway, glad you got it resolved.
