### ISSUE TITLE
YAML equals not supported?

### ISSUE THREAD

**Issue by alexec** [FasterXML/jackson-dataformat-yaml#58]
I'm used to using the following YML syntax (similar to Ansible):

~~~
url: https://www.google.co.uk
elements:
  query: id=lst-ib
  search: name=btnK
~~~

Which I would expect to be equivalent to:

~~~
url: https://www.google.co.uk
elements:
  query: 
    id: lst-ib
  search: 
    name: bank
~~~

But this cannot be parsed?

**Comment by cowtowncoder** [comment]
If SnakeYAML can parser it, dataformat module will parse it as well. But I wasn't aware that such syntax would actually be interpreted the way you expect: isn't "id=lst-ib" simply String value, and not a nested object. Would YAML syntax suggest such to indicate structured sub-properties?

**Comment by cowtowncoder** [comment]
Not sure YAML actually supports said notation; may be reopened with pointers to the spec showing expected behavior.
