### ISSUE TITLE
YAML serializer reports wrong exception

### ISSUE THREAD

**Issue by pmogren** [FasterXML/jackson-dataformat-yaml#60]
When there is a serialization error (such as a StackOverflowError due to cyclical references) the useful exception (a JsonMappingException in this example) which should be reported to the user can be masked by an unhelpful exception that occurs during YAMLGenerator.close(). Only if that exception during close is an IOException will it be ignored. Consider catching and ignoring additional exceptions that may occur during close.

Workaround:
```
        YAMLFactory factory = new YAMLFactory() {
            @Override
            protected YAMLGenerator _createGenerator(Writer out, IOContext ctxt) throws IOException {
                int feats = _yamlGeneratorFeatures;
                YAMLGenerator gen = new YAMLGenerator(ctxt, _generatorFeatures, feats,
                        _objectCodec, out, _version) {
                    @Override
                    public void close() throws IOException {
                        try {
                            super.close();
                        } catch (Exception e) {   // ADDED THIS TRY-CATCH TO FIX EXCEPTION REPORTING
                            throw new IOException(e);
                        }
                    }
                };
                // any other initializations? No?
                return gen;
            }
        };
        mapper = new ObjectMapper(factory);
```

**Comment by cowtowncoder** [comment]
This should work as expected with `jackson-databind` 2.8.0, as it can now use try-with-resources and/or `Throwable.addSuppressed()` to deal with secondary fails.
