### ISSUE TITLE
Duplicate keys

### ISSUE THREAD

**Issue by andrey-polyakov** [FasterXML/jackson-dataformat-yaml#61]
Hi,

I need keys in map structures to be checked for duplicates and rejected if found. How to enable this, of course, if it is implemented?

To be specific, I want to avoid overwriting of values in java.util.Map.

**Comment by cowtowncoder** [comment]
As a usage question, this would belong in mailing lists (jackson-user Google group).
With json backend, you coudl enable `JsonParser.Feature.STRICT_DUPLICATE_DETECTION`, but I am not sure it is supported by YAML module yet. Conversely, yaml module uses SnakeYaml for decoding so it might already be checking for that.

**Comment by cowtowncoder** [comment]
Note to self: should add a test to verify, either way.

**Comment by cowtowncoder** [comment]
Moved: https://github.com/FasterXML/jackson-dataformats-text/issues/5
