### ISSUE TITLE
Javadoc on GitHub pages out of date

### ISSUE THREAD

**Issue by michaelmior** [FasterXML/jackson-dataformat-yaml#64]
It would be great if the hosted version of the docs could be updated. Also, the Maven dependency listed in the README lists an old version. Is this intentional?

**Comment by cowtowncoder** [comment]
README is not generated automatically, so version is whatever latest happens to be. Improvement suggestions are welcome. Same is true for javadoc links from wiki page.

**Comment by michaelmior** [comment]
Any reason not to update the README to the latest version?

**Comment by cowtowncoder** [comment]
@michaelmior No objection; I usually try to update it as part of release cycle, but also accept PRs for readme, documentation.

**Comment by michaelmior** [comment]
I can put together a PR to change those two characters in the README if you want. Otherwise with the wiki updated, I'll close this. Thanks!
