### ISSUE TITLE
Add `YAMLGenerator.Feature.INDENT_ARRAYS`

### ISSUE THREAD

**Issue by qinfchen** [FasterXML/jackson-dataformat-yaml#67]
Current output and it always skips indents for arrays

```
test:
- entry1
- entry2
```

desired output

```
test:
  - entry1
  - entry2
```

**Comment by cowtowncoder** [comment]
If there is a way to make `SnakeYAML` (which this module uses for generation and parsing) use such indentation I would be happy to add a configuration feature to allow such a change.

**Comment by qinfchen** [comment]
Looks like this is supported in snakeyml 1.17 now

https://bitbucket.org/asomov/snakeyaml/issues/327/allow-customizing-block-sequence
https://bitbucket.org/asomov/snakeyaml/pull-requests/6/support-customizing-a-whitespace-before/diff

I think the change is to specify the indentation in the buildDumperOptions of YamlGenerator. I was trying to create a PR, but couldn't make project build/pass tests
```
    protected DumperOptions buildDumperOptions(int jsonFeatures, int yamlFeatures,    org.yaml.snakeyaml.DumperOptions.Version version)
    {
        opt.setIndicatorIndent(2);
        return opt;
    }
```

**Comment by cowtowncoder** [comment]
@qinfchen Ok thank you; this might be enough for me or someone else to implement the feature. I can definitely help with tests.

**Comment by cowtowncoder** [comment]
Ok; I can boost SnakeYAML dependency for 2.8.5, but feature to expose this will need to go in 2.9 I'm afraid (API change).

**Comment by qinfchen** [comment]
thanks @cowtowncoder!

**Comment by ondrej-kvasnovsky** [comment]
It works on primitive values now (tested on 2.9.0.pr4). But it seem that intending for arrays is not working on complex types. 

Here is an example. If you use this YAML as input and you read it with YAMLMapper: 
```---
tags:
  - tag:
      values:
        - "first"
        - "second"
      name: "Mathematics"
```
And then you serialize it back to YAML, it shouldn't break it. But it does add a new empty line after '-' symbol. So, the YAML gets broken like this: 
```
---
tags:
  -
  tag:
    values:
      - "first"
      - "second"
    name: "Mathematics"
```

Here is a test case to use. 

```
import com.fasterxml.jackson.dataformat.yaml.YAMLGenerator;
import com.fasterxml.jackson.dataformat.yaml.YAMLMapper;
import org.junit.Assert;
import org.junit.Test;

public class ArrayIntendingOnComplexTypesTest {

    @Test
    public void testArrayIndentation() throws Exception {
        String yamlBefore = "---\n" +
                "tags:\n" +
                "  - tag:\n" +
                "      values:\n" +
                "        - \"first\"\n" +
                "        - \"second\"\n" +
                "      name: \"Mathematics\"";

        YAMLMapper yamlMapper = new YAMLMapper().enable(YAMLGenerator.Feature.INDENT_ARRAYS);
        Object json = yamlMapper.readValue(yamlBefore, Object.class);
        String yamlAfter = yamlMapper.writeValueAsString(json);

        Assert.assertEquals(yamlBefore, yamlAfter.trim());
    }
}
```

**Comment by cowtowncoder** [comment]
Actual serialization/deserialization of YAML is delegated to `SnakeYAML` library, including indentation, so this sounds like potential bug in it (or possibly mis-configuration by Jackson?).
Version used is `1.17`, but there is one newer patch version, `1.18`. Looking at change notes:

https://bitbucket.org/asomov/snakeyaml/wiki/Changes

I think there are 2 fixes that might be relevant here:

* https://bitbucket.org/asomov/snakeyaml/issues/358/dump-with-block-setindicatorindent-2-makes
* https://bitbucket.org/asomov/snakeyaml/issues/355/dumping-long-string-values-are-not-split

of which first seems to be for very similar (if not same) issue.

I'll see if I can fix this by version upgrade.

**Comment by cowtowncoder** [comment]
Alas, it does not look like 1.18 fixed the issue; nor fixes applied so far for 1.19.

**Comment by cowtowncoder** [comment]
Ok, I added the test (thank you!), and upgrade snakeyaml dependency for jackson `2.9.1`.
Unfortunately I don't know if there is anything jackson can do here, nor exactly how to reproduce this for snakeyaml team -- I assume there is an edge case that is not handled correctly.

**Comment by ondrej-kvasnovsky** [comment]
Yes, it is a bug in SnakeYAML. Not sure if that would help, but maybe, before it is fixed in SnakeYAML, it would be nice to use this configuration (that produces valid YAML): 

```
options.setIndent(4);
options.setIndicatorIndent(2);
```

**Comment by ondrej-kvasnovsky** [comment]
If you want to replicate it in SnakeYAML, do this: 
```
            DumperOptions options = new DumperOptions();
            options.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
            options.setDefaultScalarStyle(DumperOptions.ScalarStyle.PLAIN);
            options.setPrettyFlow(true);
            options.setExplicitStart(true);
            options.setIndent(2); // default is 2, it is here to make it obvious
            options.setIndicatorIndent(2); // default is 0, if you set it to 2, it breaks YAML (and this is done in this library)
            Yaml y = new Yaml(options);
            Object load = y.load(text);
            String dump = y.dump(load);
```
