### ISSUE TITLE
Boolean-like content of string must never be unquoted

### ISSUE THREAD

**Issue by rhuss** [FasterXML/jackson-dataformat-yaml#77]
Even when `MINIMIZE_QUOTES` is set, pure boolean string content like "true" or "false" must never be unquoted, because this changes the datatype from String to boolean.

**Comment by cowtowncoder** [comment]
Ah. Took a while to follow up to understand... and yes, I think that makes sense in general.

But do you think it's something that should never be done? My experience has been that users' needs and requirements vary a lot, so just want to ensure this could not introduce a bug report in near future.
I guess it'd be possible to try to make it configurable, but then again that might be an overkill.
At most I think this does mean that I would fix it for `2.8` (but not 2.7), as risk mitigation.

Aside from that question, happy to merge. One thing we need (if not asked & received yet?) is the Contributor License Agreement:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

and the easiest way is usually to print, fill & sign, scan, email to `info` at fasterxml dot com. Needed only once, for all Jackson projects, good after that. So one-time hassle.

Looking forward to merging this in!

**Comment by rhuss** [comment]
Yes, I think so. Since you know that it is a String which you want to serialize, you should keep it a String. I you remove the quotes from `"true"` this String becomes a Boolean, which imo never is correct.

Using or not using `MINIMIZE_QUOTE` should result in the same YAML content and not one document with a String and in the other with a Boolean (its not about conversion but about simplification). 
I even wouldn't make is configurable.

And btw, the same is true for numbers: If you remove the quotes around "3.14" the String becomes a Number. So this PR is probably only half the story, however for not un-quoting strings there is already the feature `ALWAYS_QUOTE_NUMBERS_AS_STRINGS`  (which tbh should probably be better named `NEVER_UNQUOTE_NUMBERS_IN_STRINGS`). Again, imo `ALWAYS_QUOTE_NUMBERS_AS_STRINGS` should be always true (and not even configurable).

If you are more for consistency then correctness ;-) I could change this PR to go for a `ALWYAYS_QUOTE_BOOLEANS_AS_STRINGS` which would then be symmetric to the already `ALWAYS_QUOTE_NUMBERS_AS_STRINGS`.

'will mail you the  contributor-agreement later.

thanks ;-)

**Comment by cowtowncoder** [comment]
@rhuss Makes sense. Perhaps we should just go ahead with this, handle simple `boolean` case, and see if work on configurability is needed. Numbers are natural extension (was wondering about it). But one challenge at a time. :)

**Comment by rhuss** [comment]
thanks. Just mailed the CLA.
