### ISSUE TITLE
Parse Objects from YAML Object Subtree using "prefix"

### ISSUE THREAD

**Issue by marcellodesales** [FasterXML/jackson-dataformat-yaml#82]
I created the stackoverflow question http://stackoverflow.com/questions/41582765/define-prefix-root-node-for-jackson-serialization-deserialization-yaml-document. What I need is the following:

* Instead of creating multiple POJO classes to represent a subtree of objects, I'd like to use a "prefix" notation.

* Use a "prefix" to refer to the object tree to load a give POJO(s)

This approach is used on SpringBoot to refer to Properties. Is there a way to define the "prefix" as discussed in the stackoverflow, avoiding the creation of multiple POJO classes?

**Comment by cowtowncoder** [comment]
This does not appear to be specific to YAML, but if I understand it correctly it could be viewed as a request for adding something like `@JsonWrapped`, see:

https://github.com/FasterXML/jackson-databind/issues/512

if so, functionality does not yet exist. Its counterpart, `@JsonUnwrapped`, does.

**Comment by marcellodesales** [comment]
@cowtowncoder Yeah, I can see that being `@JsonUnwrapped`. I would say that @JsonUnwrapped at the Class level could give us the "prefix" option for the case I'm presenting.

**Comment by cowtowncoder** [comment]
Yes; if no issue found from `jackson-databind` (I thought there is one; if not, under `jackson-annotations`?), feel free to create one.
