### ISSUE TITLE
Can't set property naming strategy in YAMLMapper builder chain

### ISSUE THREAD

**Issue by rohanliston** [FasterXML/jackson-dataformat-yaml#84]
I'm creating a `YAMLMapper` using the builder chain as follows:

```
YAMLMapper mapper = new YAMLMapper()
        .enable(YAMLGenerator.Feature.INDENT_ARRAYS)
        .enable(YAMLGenerator.Feature.MINIMIZE_QUOTES)
        .enable(YAMLGenerator.Feature.WRITE_DOC_START_MARKER);
```

I'd like to add `.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE)` to the above block, but that method returns an `ObjectMapper`, not a `YAMLMapper`, as it comes from the base databind package.

Adding an explicit cast to `YAMLMapper` works, but it would be nice if that method could be overridden to return a `YAMLMapper` so that it can be included in the builder chain without a cast.

**Comment by cowtowncoder** [comment]
Hmmh. This is a fundamental problem and something that can not be resolve in generic manner for Jackson 2.x (for 3.x we could perhaps switch to builder-style configuration of mappers, which should work).

But for specific method it should be doable by just adding override with co-variance.

**Comment by cowtowncoder** [comment]
Will be tackled in generic fashion for Jackson 3.x.
