### ISSUE TITLE
Is there a way to disable some features from SnakeYaml

### ISSUE THREAD

**Issue by exbe** [FasterXML/jackson-dataformat-yaml#85]
SnakeYaml converts some string values into Boolean while resolving input ([link](https://bitbucket.org/asomov/snakeyaml/src/04378d05777d21d114a9cdc24976ad49c8919222/src/main/java/org/yaml/snakeyaml/resolver/Resolver.java?at=default&fileviewer=file-view-default#Resolver.java-31:33))

```
 public static final Pattern BOOL = Pattern.compile("^(?:yes|Yes|YES|no|No|NO|true|True|TRUE|false|False|FALSE|on|On|ON|off|Off|OFF)$");
```
While it is useful feature, some yamls might be converted with wrong value. Think about country code "NO", which is Norway.

Is there a way to disable or have better control over this with YamlParser features?

PS
Workaround is simple, just surround value with quotes, e.g.
```
countries:
    - AU
    - "NO"
    - MOON
```

**Comment by cowtowncoder** [comment]
@exbe At this point no. Ideally `SnakeYAML` usage would be implementation detail (to allow use of alternate decoders in future, if anyone ever implements other as-fully-featured codecs :) ).
But at the same time, it would be good to expose meaningful variations.

So: I am open to improvement ideas. If one of existing `JsonParser.Feature`s worked, those could be used as API (and result in calling suitable setters). But I don't think there's anything that quite works.

**Comment by cowtowncoder** [comment]
Moved: https://github.com/FasterXML/jackson-dataformats-text/issues/37
