### ISSUE TITLE
Emit comments

### ISSUE THREAD

**Issue by lovasko** [FasterXML/jackson-dataformat-yaml#89]
Is it please possible to emit comment lines with the keys? I could imagine this being done with an annotation for the respective class member. Also, adding whitespace, e.g. empty line would be a nice feature as well.

If this is not currently possible, could anyone please point me to the code where this magic would be happening so that I can add this feature?

Many thanks! :)

**Comment by cowtowncoder** [comment]
This is closed repository so closing. Looks like you also filed this in `jackson-dataformats-text` which is new repo.
